import { useCallback, useEffect, useState } from 'react';
import type { Run, RunReview, Workspace } from '@shared/domain/entities';
import { EmptyState } from './EmptyState';

type Tab = 'summary' | 'changes' | 'activity' | 'protocol';
const tabs: readonly [Tab, string][] = [['summary', 'Summary'], ['changes', 'Changes / Diff'], ['activity', 'Activity'], ['protocol', 'Raw Protocol']];

export const RunsView = ({ workspace, onError }: { workspace: Workspace; onError: (message: string) => void }) => {
  const [runs, setRuns] = useState<Run[]>([]); const [selected, setSelected] = useState<Run | null>(null); const [review, setReview] = useState<RunReview | null>(null); const [tab, setTab] = useState<Tab>('summary'); const [path, setPath] = useState<string | null>(null); const [diff, setDiff] = useState('');
  const refresh = useCallback(async () => { try { const next = await window.nightShift.runs.list(workspace.id); setRuns(next); setSelected((current) => next.find((run) => run.id === current?.id) ?? next[0] ?? null); } catch (error) { onError(message(error)); } }, [onError, workspace.id]);
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 1500); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);
  useEffect(() => { if (selected) void window.nightShift.runs.review(selected.id).then(setReview).catch((error: unknown) => onError(message(error))); }, [onError, selected]);
  const open = (tool: 'explorer' | 'ide' | 'terminal') => selected && void window.nightShift.runs.openWorktree(selected.id, tool).catch((error: unknown) => onError(message(error)));
  const exportReview = (kind: 'markdown' | 'json' | 'bundle') => selected && void window.nightShift.runs.exportReview(selected.id, kind).catch((error: unknown) => onError(message(error)));
  const publishCandidate = () => selected && void window.nightShift.runs.publishCandidate(selected.id).then(refresh).catch((error: unknown) => onError(message(error)));
  const createFollowUp = () => {
    const prompt = window.prompt('Corrective prompt for the follow-up Run:');
    if (selected && prompt?.trim()) void window.nightShift.runs.createFollowUp(selected.id, prompt.trim()).then(refresh).catch((error: unknown) => onError(message(error)));
  };
  const loadDiff = (nextPath: string) => selected && void window.nightShift.runs.fileDiff(selected.id, nextPath).then((next) => { setPath(nextPath); setDiff(next.content ?? next.note ?? 'No diff available.'); }).catch((error: unknown) => onError(message(error)));
  return <section className="runs-view"><div className="runs-list">{runs.length ? runs.map((run) => <button className={`run-row ${selected?.id === run.id ? 'is-selected' : ''}`} type="button" onClick={() => { setSelected(run); setTab('summary'); setPath(null); }} key={run.id}><span className={`status status-${run.status}`}>{run.status}</span><strong>{run.resolvedAgentId} · {run.resolvedModelId}</strong><small>{new Date(run.createdAt).toLocaleString()}</small></button>) : <EmptyState eyebrow="RUNS" title="Aucune tentative" detail="Les tentatives Planner persistées apparaîtront ici." />}</div><aside className="run-detail">{selected && review && <><header><div><span className={`status status-${selected.status}`}>{selected.status}</span><strong>Run {selected.id.slice(0, 8)}</strong></div><div className="run-actions">{(['explorer', 'ide', 'terminal'] as const).map((tool) => <button type="button" key={tool} onClick={() => open(tool)}>{tool}</button>)}{selected.status === 'completed' && selected.candidatePublishState !== 'published' && <button type="button" onClick={publishCandidate}>Publish Candidate</button>}{selected.status === 'completed' && selected.candidatePublishState === 'published' && selected.candidateCommitSha && <button type="button" onClick={createFollowUp}>Follow-up Run</button>}</div></header><nav className="run-tabs">{tabs.map(([value, label]) => <button type="button" className={tab === value ? 'is-active' : ''} onClick={() => setTab(value)} key={value}>{label}</button>)}</nav>{tab === 'summary' && <Summary review={review} exportReview={exportReview} />}{tab === 'changes' && <div className="run-change-grid"><div>{review.changedFiles.map((file) => <button className={path === file.path ? 'is-selected' : ''} type="button" key={file.path} onClick={() => loadDiff(file.path)}><strong>{file.kind}</strong> {file.path}<small>{file.note}</small></button>)}</div><pre>{diff || 'Select a file to view its base-relative diff.'}</pre></div>}{tab === 'activity' && <EventList events={review.activity} />}{tab === 'protocol' && <EventList events={review.rawProtocol} />}</>}</aside></section>;
};

const Summary = ({ review, exportReview }: { review: RunReview; exportReview: (kind: 'markdown' | 'json' | 'bundle') => void | null }) => <><dl><dt>Mode</dt><dd>{review.run.executionMode}</dd><dt>Agent / modèle</dt><dd>{review.run.resolvedAgentId} / {review.run.resolvedModelId}</dd><dt>Session</dt><dd>{review.run.externalSessionId ?? '—'}</dd><dt>Base SHA</dt><dd>{review.run.baseSha ?? '—'}</dd><dt>Worktree HEAD</dt><dd>{review.worktreeHead ?? review.run.finalHeadSha ?? '—'}</dd><dt>Candidate</dt><dd>{review.run.candidateBranchName ?? '—'}</dd><dt>Candidate SHA</dt><dd>{review.run.candidateCommitSha ?? '—'}</dd><dt>Publish</dt><dd>{review.run.candidatePublishState}</dd><dt>Validation</dt><dd>{review.validationStatus ?? '—'}</dd><dt>Résultat</dt><dd>{review.result ?? '—'}</dd><dt>Erreur</dt><dd>{review.failure ?? review.run.candidateFailureReason ?? '—'}</dd></dl>{review.warnings.map((warning) => <p className="run-warning" key={warning}>{warning}</p>)}<h3>Batch steps</h3>{review.batchSteps.map((step) => <p key={step.id}><strong>{step.stepIndex + 1}. {step.status}</strong> {step.prompt}</p>)}<div className="run-exports">{(['markdown', 'json', 'bundle'] as const).map((kind) => <button type="button" onClick={() => exportReview(kind)} key={kind}>Export {kind === 'bundle' ? 'ZIP bundle' : kind}</button>)}</div></>;
const EventList = ({ events }: { events: RunReview['activity'] }) => <div className="run-events">{events.length ? events.map((event) => <p key={event.id}><time>{new Date(event.timestamp).toLocaleTimeString()}</time> <strong>{event.eventType}</strong> {JSON.stringify(event.payload)}</p>) : <p className="inline-status">No events recorded.</p>}</div>;
const message = (error: unknown): string => error instanceof Error ? error.message : 'NightShift could not load Run history.';
